export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    RESET_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_FAILURE: 'RESET_PASSWORD_FAILURE',

    LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS'
};